version: "3.8"

networks:
  calibre:
    name: calibre
  traefik:
    external: true

services:
  calibre:
    image: linuxserver/calibre-web
    container_name: calibre
    environment:
      - PUID={{ uid }}
      - PGID={{ gid }}
      - TZ={{ tz }}
    volumes:
      - "{{app_root}}/web:/config"
      - "{{app_root}}/data:/library"
    restart: unless-stopped
    networks:
      - calibre
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.calibre.entrypoints: websecure
      traefik.http.routers.calibre.rule: Host(`{{subdomain_calibre}}.{{domain}}`)
      traefik.http.routers.calibre.tls: "true"
      traefik.http.services.calibre.loadbalancer.server.port: 8083
{% if ssl_use_acme %}
      traefik.http.routers.calibre.tls.certresolver: {{cert_resolver}}
{% endif %}

  calibre-server:
    image: linuxserver/calibre
    container_name: calibre-server
    environment:
      - PUID={{ uid }}
      - PGID={{ gid }}
      - TZ={{ tz }}
      - GUAC_USER={{user_calibre}}
      - GUAC_PASS={{password_calibre}}
    volumes:
      - "{{app_root}}/server:/config"
      - "{{app_root}}/data:/library"  # used to be /config/Calibre Library
    networks:
      - calibre
    restart: unless-stopped
