version: "3.8"

networks:
  traefik:
    external: true
  prometheus:
    external: true
  mysql:
    external: true

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:{{version_grafana}}
    user: "{{uid}}:0"
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SECURITY_ADMIN_PASSWORD: "{{password_admin}}"
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: {{mysql_host}}
      GF_DATABASE_NAME: {{mysql_database_grafana}}
      GF_DATABASE_USER: {{mysql_user_grafana}}
      GF_DATABASE_PASSWORD: {{mysql_pass_grafana}}
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.entrypoints: websecure
      traefik.http.routers.grafana.rule: Host(`{{subdomain_grafana}}.{{domain}}`)
      traefik.http.routers.grafana.tls: "true"
      traefik.http.services.grafana.loadbalancer.server.port: 3000
{% if ssl_use_acme %}
      traefik.http.routers.grafana.tls.certresolver: {{cert_resolver}}
{% endif %}
    volumes:
      - {{app_root}}/data/:/var/lib/grafana/
    networks:
      - traefik
      - prometheus
      - mysql
    restart: unless-stopped
